<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaaef676d76c9d25300941e115400dbf1 {
	public static $prefixLengthsPsr4 = array(
		'l' =>
			array(
				'libphonenumber\\' => 15,
			),
		'G' =>
			array(
				'Giggsey\\Locale\\' => 15,
			),
	);

	public static $prefixDirsPsr4 = array(
		'libphonenumber\\'  =>
			array(
				0 => __DIR__ . '/..' . '/giggsey/libphonenumber-for-php/src',
			),
		'Giggsey\\Locale\\' =>
			array(
				0 => __DIR__ . '/..' . '/giggsey/locale/src',
			),
	);

	public static function getInitializer( ClassLoader $loader ) {
		return \Closure::bind( function () use ( $loader ) {
			$loader->prefixLengthsPsr4 = ComposerStaticInitaaef676d76c9d25300941e115400dbf1::$prefixLengthsPsr4;
			$loader->prefixDirsPsr4    = ComposerStaticInitaaef676d76c9d25300941e115400dbf1::$prefixDirsPsr4;

		}, null, ClassLoader::class );
	}
}
